<h2><strong> Numpy 라이브러리 </strong></h2>

In [2]:
import numpy as np
alist = [[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]]
arr = np.array(alist,int)
arr[0:2:1, 0:4:1] 

#arr[행(시작값:종료값:증감값,시작값:종료값:증감값)]

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [3]:
# 행과 열에 대해서 증감값 생략, 시작값 생략, 종료값 생략

# 1. 증감값 생략
print('증감값 생략\n' ,arr[1:2,1:2])

# 2. 시작값 생략
print('시작값 생략\n', arr[:2, :3])

# 3. 종료값 생략 
print('종료값 생략\n', arr[2:, 3:])

증감값 생략
 [[2]]
시작값 생략
 [[1 2 3]
 [1 2 3]]
종료값 생략
 [[4]
 [4]]


In [4]:
# 1행에 대해서 열에 대해서 2씩 증가
x = np.array(range(15), dtype = int)
x = x.reshape(3,-1)
x[1, ::2] # 행과 열에 대해서 따로따로 표현가능 지난 정리에서 이미 끝남
x[::1, ]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

<h4>넘파이 배열 객체 다루기</h4>
<h5>배열 생성 함수 </h5>

- <strong>arange</strong> : 시작값에서 증감값을 늘려나가며 끝 값까지 계산한것<br> -><strong>arange</strong>(시작값, 끝 값 + 1, 증감값)

In [15]:
print(np.arange(0,10,1))
print(np.arange(0,10,3))
print(np.arange(0,10,0.8))
print(np.arange(30,11,-1))
print(np.arange(10,0,-1))

[0 1 2 3 4 5 6 7 8 9]
[0 3 6 9]
[0.  0.8 1.6 2.4 3.2 4.  4.8 5.6 6.4 7.2 8.  8.8 9.6]
[30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]
[10  9  8  7  6  5  4  3  2  1]


- <strong>ones</strong> : 1로만 구성된 넘파이 배열을 생성

In [17]:
print(np.ones(shape = (5,2), dtype = np.int8))


[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


- <strong>zeros</strong> : 0로만 구성된 넘파이 배열을 생성

In [18]:
np.zeros(shape = (2,2), dtype = np.float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)

- <Strong>empty</strong> : 활용가능한 메모리 공간 확보하여 반환<br>
-> 메모리 공간을 초기화하지는 않으며, 생성할 때마다 다른 값 반환

In [19]:
np.empty(shape = (2,4), dtype = np.float32)

array([[2.0457300e-29, 5.8153886e-43, 5.3265527e-39, 7.8061461e-39],
       [9.2755463e-39, 1.0561242e-38, 1.0744882e-38, 9.2755463e-39]],
      dtype=float32)

In [20]:
x=  np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- <strong>ones_like</strong> : 기존 넘파이 배열과 같은 크기로 만들어 내용을 1 로 채움

In [21]:
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

- <strong>zeros_like</strong> : 기존 넘파이 배열과 같은 크기로 만들어 내용을 0 로 채움

In [22]:
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

- <strong>identity</strong> : 단위 행렬을 생성
<br> -> 매개 변수 *n*으로 *n* x *n*  단위 행렬 생성

In [24]:
np.identity(n=3 ,dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

- <strong>eye</strong> : 시작점과 행렬 크기를 지정, 단위 행렬 생성
<br> -> *N* : 행의 개수
<br> -> *M* : 열의 개수
<br> -> *k* : 열의 값을 기준으로 하는 시작 인덱스

In [6]:
print(np.eye(N=3, M=5,k=2)) 
print()
print(np.eye(N=3, M=3, k=0))

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

- <strong>diag</strong> : 행렬의 대각 성분 값을 추출

In [10]:
print(np.diag(matrix))
print(np.diag(matrix, k=1))

[0 4 8]
[1 5]


<h5>통계 분석 함수<h5>

- <strong>uniform</strong> : 균등 분포 함수
<br>-> <strong>np.random.uniform</strong>(시작값, 끝값, 데이터 개수)

In [35]:
np.random.uniform(0,5,10)

array([1.4093936 , 2.33977732, 2.36875796, 3.36687015, 4.96711671,
       0.1702683 , 2.18828703, 3.97132454, 0.41858546, 0.88932938])

- <strong>normal</strong> : 정규분포 함수
<br>-> <strong>np.random.normal</strong>(평균값, 분산, 데이터 개수)

In [12]:
np.random.normal(0, 2, 10)

array([-1.22471768,  0.57124435,  2.27293173, -1.74241495, -2.6430677 ,
        3.21561085, -4.56465142, -1.23056622,  0.82645665,  1.86988087])

<h4>넘파이 배열 연산</h4>

<h5>연산 함수</h5>

- 연산 함수 : 배열 내부 연산을 지원하는 함수
- 축(*axis*) : 배열의 랭크가 증가할 때마다 새로운 축이 추가 되어 차원 증가
- <strong>sum</strong> : 각 요소의 합을 반환

2차원 기준 axis <br>
- 0일때는 열(세로)끼리 연산 <br>
- 1일 때는 행(가로)끼리 연산

In [16]:
test_array = np.arange(1,13).reshape(3,4)
print(test_array)
print()
print('axis = 0 -> ',test_array.sum(axis = 0))
print('axis = 1 -> ', test_array.sum(axis = 1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

axis = 0 ->  [15 18 21 24]
axis = 1 ->  [10 26 42]


In [41]:
x = np.arange(1,13).reshape(3,4)
print(x)
test_array = np.array([x,x],int)
print('shape = ', test_array.shape)
print(test_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape =  (2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [44]:
for i in range(3):
    print('axis = ', i , "---------------------")
    print(test_array.sum(axis = i))
    print()
    
# 0 은 해당 위치에 있는 것들 끼리 더해지는 것
# 1 은 각각의 열끼리 더한 것
# 2 는각각의 행끼리 더한 것

axis =  0 ---------------------
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

axis =  1 ---------------------
[[15 18 21 24]
 [15 18 21 24]]

axis =  2 ---------------------
[[10 26 42]
 [10 26 42]]



텐서가 2 2 3 4 인 텐서를 만든다

In [63]:
# 2 2 3 4 

x = [
    [[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
    [[1,2,3,4],[5,6,7,8],[9,10,11,12]]],
    [[[2,2,3,4],[5,6,7,8],[9,10,11,12]],
    [[2,2,3,4],[5,6,7,8],[9,10,11,12]]],
]
x = np.array(x)
x

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]],


       [[[ 2,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[ 2,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]]])

 axis = 0 일때, 1 과 3, 2 와 4끼리 더한 것<br>
 최상위 계층 서로가 더한것

In [64]:
x.sum(axis = 0)

array([[[ 3,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]],

       [[ 3,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]]])

axis가 1 일때 1과 2, 3과 4<br>
최상위 계층 안에서 서로 더한 것 

In [65]:
x.sum(axis = 1)

array([[[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]],

       [[ 4,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]]])

axis 가 2일때, 1, 2, 3, 4
<br>최상위 계층 바로 아래 있는 것들 내부에서 서로 더한 것


In [66]:
x.sum(axis = 2)

array([[[15, 18, 21, 24],
        [15, 18, 21, 24]],

       [[16, 18, 21, 24],
        [16, 18, 21, 24]]])

axis가 3일때 
<br> 바로 직전에는 열끼리의 합이었지만 이번엔 행끼리의 합

In [58]:
x.sum(axis = 3)

array([[[10, 26, 42],
        [10, 26, 42]],

       [[10, 26, 42],
        [10, 26, 42]]])

- <strong>mean</strong> : *axis* 축을 기준으로 평균 연산

In [19]:
test_array = np.arange(1,13).reshape(3,4)
print(test_array)
print('가로들의 평균 : ', test_array.mean(axis = 1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
가로들의 평균 :  [ 2.5  6.5 10.5]


- <strong>std</strong> : *axis* 축을 기준으로 전체 값에 대한 표준편차 연산

In [69]:
test_array.std(axis = 0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

- <strong>sqrt</strong> : 각 요소에 제곱근 연산 수행

In [70]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

<h5>연결 함수</h5>

- 연결 함수 : 두 객체 간의 결합을 지원하는 함수
- <strong>vstack</strong> : 배열을 수직으로 붙여 하나의 행렬을 생성
- <strong>hstack</strong> : 배열을 수평으로 붙여 하나의 행렬을 생성

In [22]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
print('vstack\n',np.vstack((v1,v2)))
print('hstack\n',np.hstack((v1,v2)))

vstack
 [[1 2 3]
 [4 5 6]]
hstack
 [1 2 3 4 5 6]


넘파이는 열 벡터를 표현할 수 없기 때문에 *2차원 행렬 형태*로 표현한다.

In [78]:
v1 = v1.reshape(-1,1)
v2 = v2.reshape(-1,1)
print(v1, '\n')
print(v2)

[[1]
 [2]
 [3]] 

[[4]
 [5]
 [6]]


<strong>hstack</strong> : 2차원 행렬 형태로 표현한 열 벡터를 hstack으로 연결

In [24]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6])

- <strong>consatenate</strong> : 축을 고려하여 두 개의 배열을 결합
<br> -> 스택(stack) 계열의 함수와 달리 생성될 배열과 소스가 되는 배열의 차원이 같아야함
<br> -> 두 벡터를 결합하고 싶다면, 해당 벡터를 일단 2차원 배열 꼴로 변환 후 행렬로 나타내야함.

In [25]:
v1 = np.array([[1,2,3]])
v2 = np.array([[4,5,6]])
np.concatenate((v1,v2),axis = 0)

array([[1, 2, 3],
       [4, 5, 6]])

- 전치행렬 <strong>T</strong>

In [27]:
v1 = np.array([1,2,3,4]).reshape(2,2)
v2 = np.array([[5,6]]).T
print('v1 \n',v1)
print('v2 \n',v2)

v1 
 [[1 2]
 [3 4]]
v2 
 [[5]
 [6]]


- 벡터의 내적(dotproduct) : 두 배열 간의 곱셈
<br> -> 두개의 행렬에서 첫 번째 행렬의 열 크기와 두 번째 행렬의 행 크기가 동일해야함
<br> -> m x n행렬과 m x l행렬을 내적하면 m x l 행렬 생성한다.

In [28]:
x1 = np.arange(1,7).reshape(2,3)
x2 = np.arange(1,7).reshape(3,2)
x1.dot(x2)

array([[22, 28],
       [49, 64]])

-  브로드 캐스팅 연산 : 전체 행렬에 다 계산을 해주는 연산
<br> -> 하나의 행렬과 스칼라 값들 간의 연산이나 행렬과 벡터 간의 연산

In [29]:
x = np.arange(1,13).reshape(4,3)
x+3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

<h4>비교 연산과 데이터 추출</h4>
<h5>비교 연산</h5>

- 연산 결과는 항상 불린형을 가진 배열로 추출
- 하나의 스칼라 값과 벡터 간의 비교연산은 벡터 내 전체 요소에 적용

In [30]:
v = np.arange(10,40,10)
v > 16

array([False,  True,  True])

- <strong>all</strong> : 배열 내부의 모든 값이 참일 때는 *True*, 하나라도 아니면 *False*를 나타낸다.
- <strong>any</strong> : 배열 내부의 값 중 하나라도 참일때는 True, 모두 거짓일때는 *False*를 반환한다.

In [85]:
x = np.array([1,2,3,4,5,6,7,8,9])
print((x>3).all())
print((x>3).any())

False
True


<h5>인덱스 반환 함수</h5>

- <strong>where</strong> : 배열이 불린형으로 이루어졌을때 참인 값들의 인덱스를 반환
<br>-> True, false인 경우의 값을 지정해줄 수도 있다. 

In [32]:
x = np.array([4,6,7,3,2])
print(np.where(x>5))
print(np.where(x>5,10,20))

(array([1, 2], dtype=int64),)
[20 10 10 20 20]


<h5>정렬된 값의 인덱스를 반환해주는 함수</h5>

- <strong>argsort</strong> : 배열 내 값들을 작은 순서대로 인덱스 반환
- <strong>argmax</strong> : 배열 내 값들 중 가장 큰 값의 인덱스를 반환
- <strong>argmin</strong> : 배열 내 값들 중 가장 큰 값의 인덱스를 반환


In [33]:
x = np.array([4,6,7,3,2])
print('argsort : ',np.argsort(x))
print('argmax : ',np.argmax(x))
print('argmin : ',np.argmin(x))

argsort :  [4 3 0 1 2]
argmax :  2
argmin :  4


<h5>인덱스를 활용한 데이터 추출</h5>
<h4>불린 인덱스</h4>

- 불린 인덱스 : 배열에 있는 값들을 반환할 특정 조건을 불린형의 배열에 넣어서 추출
<br> -> 인덱스에 들어가는 배열은 불린형이어야 함
<br> -> 불린형 배열과 추출 대상이 되는 배열의 구조가 같아야 함

In [37]:
x = np.array([4,6,7,3,2])
print('x > 3 : ', x > 3)
cond = x > 3
print('cond : ',x[cond])
print('x.shape : ', x.shape )
print('cond.shape : ', cond.shape)


x > 3 :  [ True  True  True False False]
cond :  [4 6 7]
x.shape :  (5,)
cond.shape :  (5,)


<h5>팬시 인덱스<h5>

- 팬시인덱스 : 정수형 배열의 값을 사용하여 해당 정수의 인덱스에 위치한 값을 반환
<br> - 인덱스 항목에 넣을 배열은 정수로만 구성되어야 함
<br> - 정수 값의 범위는 대상이 되는 배열이 가지는 인덱스 범위 내 대상이 되는 배열과 인덱스 배열의 구조가 같을 필요는 없음

In [38]:
x = np.array([4,6,7,3,2])
cond = np.array([1,2,0,2,2,2,],int)
print('x[cond] : ',x[cond])
print('x.take(cond) : ',x.take(cond))

x[cond] :  [6 7 4 7 7 7]
x.take(cond) :  [6 7 4 7 7 7]


In [40]:
x = np.array([[1,4],[9,16]])
a = np.array([0,1,1,1,0,0],int)
b = np.array([0,0,0,1,1,1],int)
x[a,b]

array([ 1,  9,  9, 16,  4,  4])